version: "2"
linters:
  default: standard
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - errname
    - fatcontext
    - funcorder
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gosec
    - iface
    - importas
    - intrange
    - loggercheck
    - makezero
    - mnd
    - nilerr
    - nilnil
    - nolintlint
    - noctx
    - perfsprint
    - prealloc
    - predeclared
    - recvcheck
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - zerologlint
run:
  timeout: 5m
  concurrency: 4
  tests: false
